import product1 from "./assets/26 Stylish Armchairs For All Budgets.jpg";
import product2 from "./assets/494ebdef-5108-4074-85b4-675dc70b7d35.jpg";
import product3 from "./assets/cea7d268-7e91-453c-ad02-2a627daeed5e.jpg";
import product4 from "./assets/It's back! The Range chair that caused a shopping frenzy last year is now available in navy.jpg";
import product5 from "./assets/Oversized Chaise Lounge Chairs - Foter.jpg";
import product6 from "./assets/Panton Chair Anniversary Competition and Charity Auction.jpg";
import product7 from "./assets/Vladimir Kagan's Annecy Collection - his final work - dares you to decide_ Furniture designer - or sculptor_ - Retro Renovation.jpg";
import product8 from "./assets/Wave - Stratum Bespoke.jpg";
import product9 from "./assets/Shell.jpg";
import product10 from "./assets/Avocado.jpg";
import product11 from "./assets/Wood Rocking Sofa Chair_ Exceptional Comfort and Style - Style A.jpg";
import product12 from "./assets/Wooden Chair Showing Movement and Material Conscious Design.jpg";

export const PRODUCTS = [
  {
    id: 1,
    productImage: product1,
    productName: "Stylish Armchair",
    price: 119.99,
    description: "Comfortable and stylish armchair.",
    color: "Blue",
    material: "Fabric",
    dimensions: "30x30x35 inches",
    weight: "15 lbs",
  },
  {
    id: 2,
    productImage: product2,
    productName: "Modern Armchair",
    price: 129.99,
    description: "Modern design armchair for any space.",
    color: "Gray",
    material: "Leather",
    dimensions: "32x30x36 inches",
    weight: "18 lbs",
  },
  {
    id: 3,
    productImage: product3,
    productName: "Luxury Armchair",
    price: 139.99,
    description: "Luxury armchair with premium materials.",
    color: "White",
    material: "Velvet",
    dimensions: "31x31x34 inches",
    weight: "20 lbs",
  },
  {
    id: 4,
    productImage: product4,
    productName: "Navy Armchair",
    price: 149.99,
    description: "Elegant navy armchair for stylish living.",
    color: "Navy",
    material: "Suede",
    dimensions: "29x29x33 inches",
    weight: "17 lbs",
  },
  {
    id: 5,
    productImage: product5,
    productName: "Oversized Chaise Lounge",
    price: 159.99,
    description: "Oversized chaise lounge for ultimate comfort.",
    color: "Red",
    material: "Microfiber",
    dimensions: "35x35x40 inches",
    weight: "25 lbs",
  },
  {
    id: 6,
    productImage: product6,
    productName: "Panton Chair",
    price: 169.99,
    description: "Classic Panton chair design.",
    color: "Black",
    material: "Plastic",
    dimensions: "28x28x32 inches",
    weight: "10 lbs",
  },
  {
    id: 7,
    productImage: product7,
    productName: "Annecy Collection Chair",
    price: 179.99,
    description: "Part of the Annecy Collection, designed by Vladimir Kagan.",
    color: "Green",
    material: "Wood",
    dimensions: "30x30x35 inches",
    weight: "22 lbs",
  },
  {
    id: 8,
    productImage: product8,
    productName: "Wave Chair",
    price: 189.99,
    description: "Unique wave chair for modern interiors.",
    color: "Blue",
    material: "Metal",
    dimensions: "31x31x34 inches",
    weight: "18 lbs",
  },
  {
    id: 9,
    productImage: product9,
    productName: "Shell Chair",
    price: 199.99,
    description: "A unique shell-inspired design for a modern look.",
    color: "Beige",
    material: "Plastic",
    dimensions: "29x29x33 inches",
    weight: "16 lbs",
  },
  {
    id: 10,
    productImage: product10,
    productName: "Avocado Chair",
    price: 209.99,
    description: "A quirky and fun chair inspired by avocados.",
    color: "Green",
    material: "Fabric",
    dimensions: "32x32x36 inches",
    weight: "19 lbs",
  },
  {
    id: 11,
    productImage: product11,
    productName: "Rocking Sofa Chair",
    price: 219.99,
    description: "Exceptional comfort and style in a rocking chair.",
    color: "Brown",
    material: "Wood",
    dimensions: "34x34x38 inches",
    weight: "24 lbs",
  },
  {
    id: 12,
    productImage: product12,
    productName: "Movement Conscious Chair",
    price: 229.99,
    description: "Designed with movement and material consciousness.",
    color: "Yellow",
    material: "Plastic",
    dimensions: "28x28x32 inches",
    weight: "15 lbs",
  },
  
  {
    id: 13,
    productImage: product1,
    productName: "Accent Chair",
    price: 239.99,
    description: "A stylish accent chair perfect for any living space.",
    color: "Blue",
    material: "Fabric",
    dimensions: "30x30x35 inches",
    weight: "15 lbs",
  },
  {
    id: 14,
    productImage: product2,
    productName: "Comfort Chair",
    price: 249.99,
    description: "A chair that combines comfort and style.",
    color: "Gray",
    material: "Leather",
    dimensions: "32x30x36 inches",
    weight: "18 lbs",
  },
  {
    id: 15,
    productImage: product3,
    productName: "Elegant Chair",
    price: 259.99,
    description: "An elegant chair for luxurious interiors.",
    color: "White",
    material: "Velvet",
    dimensions: "31x31x34 inches",
    weight: "20 lbs",
  },
  {
    id: 16,
    productImage: product4,
    productName: "Designer Chair",
    price: 269.99,
    description: "A designer chair that stands out.",
    color: "Navy",
    material: "Suede",
    dimensions: "29x29x33 inches",
    weight: "17 lbs",
  },
  {
    id: 17,
    productImage: product5,
    productName: "Vintage Chair",
    price: 279.99,
    description: "A vintage chair with a modern twist.",
    color: "Red",
    material: "Microfiber",
    dimensions: "35x35x40 inches",
    weight: "25 lbs",
  },
  {
    id: 18,
    productImage: product6,
    productName: "Retro Chair",
    price: 289.99,
    description: "A retro chair that adds character.",
    color: "Black",
    material: "Plastic",
    dimensions: "28x28x32 inches",
    weight: "10 lbs",
  },
  {
    id: 19,
    productImage: product7,
    productName: "Classic Chair",
    price: 299.99,
    description: "A classic chair for timeless appeal.",
    color: "Green",
    material: "Wood",
    dimensions: "30x30x35 inches",
    weight: "22 lbs",
  },
  {
    id: 20,
    productImage: product8,
    productName: "Modern Chair",
    price: 309.99,
    description: "A modern chair for contemporary spaces.",
    color: "Blue",
    material: "Metal",
    dimensions: "31x31x34 inches",
    weight: "18 lbs",
  },
  {
    id: 21,
    productImage: product9,
    productName: "Minimalist Chair",
    price: 319.99,
    description: "A minimalist chair with sleek design.",
    color: "Beige",
    material: "Plastic",
    dimensions: "29x29x33 inches",
    weight: "16 lbs",
  },
  {
    id: 22,
    productImage: product10,
    productName: "Quirky Chair",
    price: 329.99,
    description: "A quirky chair for fun interiors.",
    color: "Green",
    material: "Fabric",
    dimensions: "32x32x36 inches",
    weight: "19 lbs",
  },
  {
    id: 23,
    productImage: product11,
    productName: "Rocking Chair",
    price: 339.99,
    description: "A rocking chair with modern design.",
    color: "Brown",
    material: "Wood",
    dimensions: "34x34x38 inches",
    weight: "24 lbs",
  },
  {
    id: 24,
    productImage: product12,
    productName: "Conscious Chair",
    price: 349.99,
    description: "A chair designed with consciousness.",
    color: "Yellow",
    material: "Plastic",
    dimensions: "28x28x32 inches",
    weight: "15 lbs",
  },
  {
    id: 25,
    productImage: product1,
    productName: "Stylish Armchair",
    price: 359.99,
    description: "A stylish armchair for your living room.",
    color: "Blue",
    material: "Fabric",
    dimensions: "30x30x35 inches",
    weight: "15 lbs",
  },
  {
    id: 26,
    productImage: product2,
    productName: "Modern Armchair",
    price: 369.99,
    description: "A modern armchair for stylish spaces.",
    color: "Gray",
    material: "Leather",
    dimensions: "32x30x36 inches",
    weight: "18 lbs",
  },
  {
    id: 27,
    productImage: product3,
    productName: "Luxury Armchair",
    price: 379.99,
    description: "A luxury armchair for elegant interiors.",
    color: "White",
    material: "Velvet",
    dimensions: "31x31x34 inches",
    weight: "20 lbs",
  },
  {
    id: 28,
    productImage: product4,
    productName: "Navy Armchair",
    price: 389.99,
    description: "A navy armchair with elegant design.",
    color: "Navy",
    material: "Suede",
    dimensions: "29x29x33 inches",
    weight: "17 lbs",
  },
  {
    id: 29,
    productImage: product5,
    productName: "Chaise Lounge",
    price: 399.99,
    description: "A chaise lounge for ultimate relaxation.",
    color: "Red",
    material: "Microfiber",
    dimensions: "35x35x40 inches",
    weight: "25 lbs",
  },
  {
    id: 30,
    productImage: product6,
    productName: "Panton Chair",
    price: 409.99,
    description: "The classic Panton chair design.",
    color: "Black",
    material: "Plastic",
    dimensions: "28x28x32 inches",
    weight: "10 lbs",
  },
];

const Product = {
  getAllProducts() {
    return new Promise((resolve) => {
      setTimeout(() => {
        resolve(PRODUCTS);
      }, 2000); // Simulate delay
    });
  },

  getProductById(id) {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        const product = PRODUCTS.find((product) => product.id === id);
        if (product) {
          resolve(product);
        } else {
          reject(new Error(`Product with id ${id} not found`));
        }
      }, 2000); // Simulate delay
    });
  },
};

export default Product;
